import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import ThemeRoot from "@/utils/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-merriweather",
});

export const metadata = {
  title: "BookSwap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  suppressHydrationWarning className={`${inter.variable} ${merriweather.variable}`}>
      <body className="font-sans antialiased">
        <ReduxProvider>
          <ThemeRoot attribute="class" enableSystem defaultTheme="system">
            {children}
          </ThemeRoot>
        </ReduxProvider>
      </body>
    </html>
  );
}
